### ISSUE TITLE
Unhandled exception causes rpttoxml to crash

### ISSUE THREAD

**Issue by eshultz** [ajryan/RptToXml#15]
I get this error on one particular report of ours. Please message me if you want me to help you reproduce the error. I'm unsure where the 0x1F is coming from.

```
Unhandled Exception: System.ArgumentException: '', hexadecimal value 0x1F, is an invalid character.
   at System.Xml.XmlUtf8RawTextWriter.InvalidXmlChar(Int32 ch, Byte* pDst, Boolean entitize)
   at System.Xml.XmlUtf8RawTextWriter.WriteAttributeTextBlock(Char* pSrc, Char* pSrcEnd)
   at System.Xml.XmlUtf8RawTextWriter.WriteString(String text)
   at System.Xml.XmlUtf8RawTextWriterIndent.WriteString(String text)
   at System.Xml.XmlWellFormedWriter.WriteString(String text)
   at System.Xml.XmlWriter.WriteAttributeString(String localName, String value)
   at RptToXml.RptDefinitionWriter.GetDataDefinition(ReportDocument report, XmlWriter writer)
   at RptToXml.RptDefinitionWriter.ProcessReport(ReportDocument report, XmlWriter writer)
   at RptToXml.RptDefinitionWriter.WriteToXml(XmlWriter writer)
   at RptToXml.RptDefinitionWriter.WriteToXml(String targetXmlPath)
   at RptToXml.Program.Main(String[] args)
```

**Comment by ajryan** [comment]
Can you please upload an example report that exhibits this behavior to public dropbox or similar?

This seems like an encoding issue and it will be a lot easier to track down with a reproduction case.

Thanks for reporting!

**Comment by eshultz** [comment]
Unfortunately I can't share this specific report but let me see if I can recreate the issue by inserting the control character somewhere in a blank report.

**Comment by ajryan** [comment]
You can email the report to the address on my Github profile if you are comfortable doing so.

**Comment by eshultz** [comment]
I just built the latest version and the error is no longer present! My apologies. 

Looks like it is handled appropriately: 

```
<Group ConditionField="{@zx&#x1F;_FormatLoc}" />
```

**Comment by ajryan** [comment]
Oh good!
