### ISSUE TITLE
Unhandled Exception: System.ArgumentException: Font 'Monotype Corsiva' does not support style 'Bold'.

### ISSUE THREAD

**Issue by sunk818** [ajryan/RptToXml#30]
Dumping c:\docs\report.rpt
Loaded report
Writing to XML
Writing report
Writing header info

Unhandled Exception: System.ArgumentException: Font 'Monotype Corsiva' does not support style 'Bold'.
   at System.Drawing.Font.CreateNativeFont()
   at System.Drawing.Font.Initialize(FontFamily family, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   at System.Drawing.Font.Initialize(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   at System.Drawing.Font..ctor(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet)
   at CrystalDecisions.CrystalReports.Engine.Migration.FormatConverter.EROMFontToDNETFont(ISCRFont eromFont)
   at CrystalDecisions.CrystalReports.Engine.FieldObject.get_Font()
   at RptToXml.RptDefinitionWriter.GetReportObjects(Section section, ReportDocument report, XmlWriter writer) in c:\Development\RptToXml\RptToXml\RptDefinitionWriter.cs:line 865
   at RptToXml.RptDefinitionWriter.GetSections(Area area, ReportDocument report, XmlWriter writer) in c:\Development\RptToXml\RptToXml\RptDefinitionWriter.cs:line 800
   at RptToXml.RptDefinitionWriter.GetAreas(ReportDocument report, XmlWriter writer) in c:\Development\RptToXml\RptToXml\RptDefinitionWriter.cs:line 776
   at RptToXml.RptDefinitionWriter.GetReportDefinition(ReportDocument report, XmlWriter writer) in c:\Development\RptToXml\RptToXml\RptDefinitionWriter.cs:line 758
   at RptToXml.RptDefinitionWriter.ProcessReport(ReportDocument report, XmlWriter writer) in c:\Development\RptToXml\RptToXml\RptDefinitionWriter.cs:line 123
   at RptToXml.RptDefinitionWriter.WriteToXml(XmlWriter writer) in c:\Development\RptToXml\RptToXml\RptDefinitionWriter.cs:line 69
   at RptToXml.RptDefinitionWriter.WriteToXml(String targetXmlPath) in c:\Development\RptToXml\RptToXml\RptDefinitionWriter.cs:line 60
   at RptToXml.Program.Main(String[] args) in c:\Development\RptToXml\RptToXml\Program.cs:line 61

**Comment by ajryan** [comment]
Does the designer throw an error when you load this report?

**Comment by sunk818** [comment]
No. Desktop client opens the rpt file just fine

**Comment by ajryan** [comment]
still seems like the right fix is to edit the report and remove the invalid bold property. the exception is being thrown from inside the crystal API.

**Comment by sunk818** [comment]
The workaround is to either remove the font from your font library, or as you can the style (remove bold), or change to a different font all together.
