### ISSUE TITLE
SAP error when trying to access non-existent formula for group name

### ISSUE THREAD

**Issue by christopherpickering** [ajryan/RptToXml#45]
When trying to get the formula for a group name, and the formula does not exist, the SAP DLL is throwing an error causing RptToXml to crash.

Here's the message:
```sh
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at CrystalDecisions.ReportAppServer.DataDefModel.GroupNameFieldClass.get_FormulaForm()
   at CrystalDecisions.CrystalReports.Engine.GroupNameFieldDefinition.get_FormulaName()
   at RptToXml.RptDefinitionWriter.GetFieldObject(Object fo, eportDocument report, XmlWriter writer) in C:\Users\chris-pickering\Documents\r_source\rpttoxml\RptToXml\RptDefinitionWriter.cs:line 445
   at RptToXml.RptDefinitionWriter.GetDataDefinition(ReportDocument report, XmlWriter riter) in C:\Users\chris-pickering\Documents\r_source\rpttoxml\RptToXml\RptDefinitionWriter.cs:line 383
   at RptToXml.RptDefinitionWriter.ProcessReport(ReportDocument report, XmlWriter writer) in C:\Users\chris-pickering\Documents\r_source\rpttoxml\RptToXml\RptDefinitionWriter.cs:line 127
   at RptToXml.RptDefinitionWriter.WriteToXml(XmlWriter writer)in :\Users\chris-pickering\Documents\r_source\rpttoxml\RptToXml\RptDefinitionWriter.cs:line 71
   at RptToXml.RptDefinitionWriter.WriteToXml(String targetXmlPath) in C:\Users\chris-pickering\Documents\r_source\rpttoxml\RptToXml\RptDefinitionWriter.cs:line 62
   at RptToXml.Program.Main(String[] args) in C:\Users\chris-pickering\Documents\r_source\rpttoxml\RptToXml\Program.cs:line 62
```

I've logged the issue with SAP (https://answers.sap.com/questions/13526349/unhandled-exception-systemaccessviolationexception.html?childToView=13526461) but will also put a PR to catch this exception so we can continue running RptToXml until SAP's resolution comes.

**Comment by christopherpickering** [comment]
It looks as though SAP probably won't fix this https://answers.sap.com/questions/13526349/unhandled-exception-systemaccessviolationexception.html?childToView=13526983.
