### ISSUE TITLE
Runtime error running RptToXml

### ISSUE THREAD

**Issue by AlexGeller1** [ajryan/RptToXml#49]
Hi,

I am trying to run RptToXML. Following the link in README.md (https://www.sap.com/cmp/td/sap-crystal-reports-visual-studio-trial.html) I have downloaded and installed "[SAP Crystal Reports for Visual Studio (SP31) runtime engine for .NET framework MSI " (CRforVS_redist_install_64bit_13_0_3). 

I am starting it from a .bat with the following content:
set "PATH=%PATH%;C:\Program Files (x86)\SAP BusinessObjects\Crystal Reports for .NET Framework 4.0\Common\SAP BusinessObjects Enterprise XI 4.0\win64_x64;C:\tmp\Rpt2xml\Release-1.1.4"
RptToXml "Examples/Examples/ASP-RAS Sample/Last Year's Sales.rpt" output.xml

I get the following error:
C:\tmp\Rpt2xml>RptToXml "Examples/Examples/ASP-RAS Sample/Last Year's Sales.rpt" output.xml
Dumping Examples/Examples/ASP-RAS Sample/Last Year's Sales.rpt

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'CrystalDecisions.ReportAppServer.ClientDoc, Version=13.0.4000.0, Culture=neutral, PublicKeyToken=692fbea5521e1304' or one of its dependencies. The system cannot find the file specified.
   at RptToXml.RptDefinitionWriter..ctor(String filename)
   at RptToXml.Program.Main(String[] args) in C:\Users\chris-pickering\Documents\r_source\rpttoxml_fork\RptToXml\Program.cs:line 58

Help is greatly appreciated.

Thanks in advance,
Alex

**Comment by christopherpickering** [comment]
Hi,

It looks like you need to install the other bitness of SAP as well. Somehow only one of the bit install has the files needed :) 

The missing DLL should be in your crystal install - 

For me it shows in this folder. I wonder if you need to add the `\dotnet` to your path? Is the dll in this path?
```
C:\Program Files (x86)\SAP BusinessObjects\Crystal Reports for .NET Framework 4.0\Common\SAP BusinessObjects Enterprise XI 4.0\win32_x86\dotnet\
```

![image](https://user-images.githubusercontent.com/17788706/159363681-2a70426c-07a5-4048-944e-14a26c613b02.png)

You can always copy the dll from here into the RptToXml folder as well.

**Comment by AlexGeller1** [comment]
Thanks for the quick response! I added the dotnet directory to the path but it contains only one file on my system:
![image](https://user-images.githubusercontent.com/87009702/159364939-ddd1b6ee-2650-42bc-bd3e-203e89c2f587.png)

**Comment by christopherpickering** [comment]
No problem, You need to install both of these:

> Install the SAP frameworks (probably need 32-bit and 64-bit):
> 
> SAP Crystal Reports for Visual Studio (SP##) runtime engine for .NET framework MSI (32-bit)
> SAP Crystal Reports for Visual Studio (SP##) runtime engine for .NET framework MSI (64-bit)

**Comment by AlexGeller1** [comment]
I now installed the 32 bit version. As a result I have an additional directory win32_x86 and win32_x86\dotnet. The content of the 64 bit dotnet directory didn't change and the new 32 bit dotnet directory contains the same single file (CrystalDecisions.Data.AdoDotNetInterop.dll). 
To be sure I did:
```shell
ag@alexdell /cygdrive/c/Program Files (x86)
$ find . -name CrystalDecisions.*
./SAP BusinessObjects/Crystal Reports for .NET Framework 4.0/Common/SAP BusinessObjects Enterprise XI 4.0/win32_x86/dotnet/CrystalDecisions.Data.AdoDotNetInterop.dll
./SAP BusinessObjects/Crystal Reports for .NET Framework 4.0/Common/SAP BusinessObjects Enterprise XI 4.0/win64_x64/dotnet/CrystalDecisions.Data.AdoDotNetInterop.dll
```

**Comment by christopherpickering** [comment]
It sounds like the sap download is messed up. Do they let you download other versions? I'm putting the files on wetransfer and will give you a link when they upload.

**Comment by AlexGeller1** [comment]
Great thanks! This is what the download page looks like:
![image](https://user-images.githubusercontent.com/87009702/159371430-a78bcb27-87d9-4886-aee0-3af7c5757a69.png)

**Comment by christopherpickering** [comment]
Cool, and these are what you got? 
![image](https://user-images.githubusercontent.com/17788706/159371542-db5e59e1-8297-4309-811f-8a2d7e81f9ea.png)

**Comment by AlexGeller1** [comment]
No, I downloaded the Runtime engines as described in README.md

**Comment by christopherpickering** [comment]
yeah sorry :) The files are still uploading. Its like 1g.

**Comment by christopherpickering** [comment]
https://we.tl/t-jKuClL8hW8

**Comment by AlexGeller1** [comment]
Thanks a lot! I works now:
```shell
C:\tmp\Rpt2xml>RptToXml "Examples/Examples/ASP-RAS Sample/Last Year's Sales.rpt" output.xml
Dumping Examples/Examples/ASP-RAS Sample/Last Year's Sales.rpt
Loaded report
Writing to XML
Writing report
Writing header info

C:\tmp\Rpt2xml>
```

**Comment by christopherpickering** [comment]
Nice! I'm glad it worked! I wonder what was up w/ the sap downloads lol, sometimes they make me wonder 😁

**Comment by AlexGeller1** [comment]
Thanks again. I am closing this now.
